.PHONY: all build test test-update cover docs-cli bench lint spell fmt tidy clean run license license-check license-fix pre-commit-install pre-commit fuzz-config-hcl fuzz-config-json jsonschema

BIN            := bin/open-inspector
PKG            := ./...
GOFLAGS        ?=
BENCH          ?= .
BENCHPKG       ?= ./...
MODULE         := $(shell go list -m)
COVERAGE_OUT   := coverage.out
COVERAGE_DOC   := docs/test-coverage.md
ADDLICENSE     := go run github.com/google/addlicense@v1.2.0
LICENSE_HEADER := .licenseheader.tmpl
# Directories containing source files that must carry the MPL header.
# Extend this list as new top-level source dirs are added.
LICENSE_PATHS  := cmd pkg

all: fmt lint spell license-fix test build docs-cli

build:
	@mkdir -p bin
	go build $(GOFLAGS) -o $(BIN) ./cmd/open-inspector

test:
	go test $(GOFLAGS) -race -count=1 $(PKG)

test-update:
	go test ./pkg/config -run TestLoad_Snapshots -update

# Run the test suite with coverage and regenerate the coverage report at
# $(COVERAGE_DOC). The per-package table and total are derived from a
# single test run; the raw profile is left in $(COVERAGE_OUT) (gitignored)
# for `go tool cover -html`.
cover:
	@summary=$$(mktemp); \
	go test $(GOFLAGS) -covermode=atomic -coverprofile=$(COVERAGE_OUT) $(PKG) > $$summary 2>&1 \
		|| { cat $$summary; rm -f $$summary; exit 1; }; \
	cat $$summary; \
	total=$$(go tool cover -func=$(COVERAGE_OUT) | awk '/^total:/ {print $$NF}'); \
	{ \
		echo "# Test coverage"; \
		echo; \
		echo "Generated by \`make cover\`; do not edit by hand."; \
		echo; \
		echo "**Total: $$total**"; \
		echo; \
		echo "| Package | Coverage |"; \
		echo "| --- | --- |"; \
		awk -v module="$(MODULE)" '/coverage:/ { \
			pkg=""; cov=""; \
			for (i = 1; i <= NF; i++) { \
				if ($$i ~ /^github\.com\//) pkg = $$i; \
				if ($$i ~ /%$$/) cov = $$i; \
			} \
			if (pkg == "") next; \
			rel = pkg; sub("^" module "/?", "", rel); if (rel == "") rel = "."; \
			printf "| %s | %s |\n", rel, cov; \
		}' $$summary | sort; \
	} > $(COVERAGE_DOC); \
	rm -f $$summary; \
	echo "wrote $(COVERAGE_DOC) (total $$total)"

# Run Go benchmarks (no -race; benchmarks measure realistic throughput).
# Override BENCH to select benchmarks and BENCHPKG to scope packages, e.g.
#   make bench BENCH=BenchmarkInspect BENCHPKG=./pkg/inspector
bench:
	go test -run '^$$' -bench '$(BENCH)' -benchmem $(BENCHPKG)

lint:
	golangci-lint run

# Spell-check source, comments, and docs (config in .codespellrc).
spell:
	codespell

fmt:
	gofmt -s -w $(LICENSE_PATHS)
	go vet $(PKG)

docs-cli:
	rm -rf docs/cli docs/man
	mkdir -p docs/cli docs/man
	go run ./cmd/docgen

# Fuzz the config loader for a short, local-friendly burst. CI runs these
# longer on a weekly cron (.github/workflows/fuzz.yml).
fuzz-config-hcl:
	go test -run '^$$' -fuzz=FuzzConfigLoader_HCL -fuzztime=30s ./pkg/config

fuzz-config-json:
	go test -run '^$$' -fuzz=FuzzConfigLoader_JSON -fuzztime=30s ./pkg/config

# Regenerate the JSON Schema for the --json output (docs/schema/v1.{json,md})
# from pkg/model.Module. CI diff-checks the committed output.
jsonschema:
	go run ./cmd/jsonschemagen

tidy:
	go mod tidy

run: build
	$(BIN)

clean:
	rm -rf bin
	rm -f $(COVERAGE_OUT)

# Add the MPL-2.0 header to any source file that is missing it.
license:
	$(ADDLICENSE) -f $(LICENSE_HEADER) $(LICENSE_PATHS)

# Fail (non-zero exit) if any source file is missing the MPL-2.0 header.
# Used by CI.
license-check:
	$(ADDLICENSE) -check -f $(LICENSE_HEADER) $(LICENSE_PATHS)

# Run license-check; if it fails, auto-apply headers and re-check so a
# locally-missing header doesn't abort `make all`.
license-fix:
	@$(ADDLICENSE) -check -f $(LICENSE_HEADER) $(LICENSE_PATHS) || { \
		echo "license-check failed; applying headers and retrying..."; \
		$(ADDLICENSE) -f $(LICENSE_HEADER) $(LICENSE_PATHS) && \
		$(ADDLICENSE) -check -f $(LICENSE_HEADER) $(LICENSE_PATHS); \
	}

# Install pre-commit + pre-push hooks defined in .pre-commit-config.yaml.
pre-commit-install:
	pre-commit install --install-hooks
	pre-commit install --hook-type pre-push

# Run every hook against every tracked file (useful in CI and after big
# edits).
pre-commit:
	pre-commit run --all-files
