// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Command docgen generates the CLI markdown docs and man pages from the
// cobra command tree.
package main

import (
	"log"
	"os"
	"path/filepath"
	"regexp"

	"github.com/remoterabbit/open-inspector/cmd/open-inspector/cmd"
	"github.com/spf13/cobra/doc"
)

// main writes the markdown CLI docs to docs/cli and the man pages to
// docs/man, walking the static cobra command tree exposed by cmd.Root.
func main() {
	root := cmd.Root()

	// Markdown CLI docs.
	if err := doc.GenMarkdownTree(root, "docs/cli"); err != nil {
		log.Fatalf("genmarkdown: %v", err)
	}

	// Man pages. We deliberately leave GenManHeader.Date unset; cobra would
	// default it to time.Now(), but we strip the resulting timestamps below
	// so the generated pages are reproducible.
	header := &doc.GenManHeader{
		Title:   "OPEN-INSPECTOR",
		Section: "1",
		Source:  "open-inspector " + cmd.Version,
	}
	if err := doc.GenManTree(root, header, "docs/man"); err != nil {
		log.Fatalf("genman: %v", err)
	}
	if err := stripManTimestamps("docs/man"); err != nil {
		log.Fatalf("strip man timestamps: %v", err)
	}
}

// Cobra stamps the generation date into two places in every man page: the
// .TH title line and the trailing HISTORY section. Both change on each run,
// which produces noisy diffs. These patterns blank the date while keeping
// the surrounding structure (an empty .TH date field is valid roff, and the
// "Auto generated by spf13/cobra" attribution is preserved).
var (
	manTitleDate   = regexp.MustCompile(`(?m)^(\.TH (?:"[^"]*" ){2})"[^"]*"`)
	manHistoryDate = regexp.MustCompile(`(?m)^\d{1,2}-[A-Za-z]{3}-\d{4} (Auto generated by spf13/cobra)$`)
)

// stripManTimestamps rewrites every *.1 file under dir to remove the
// nondeterministic generation date from the .TH header and HISTORY footer.
func stripManTimestamps(dir string) error {
	paths, err := filepath.Glob(filepath.Join(dir, "*.1"))
	if err != nil {
		return err
	}
	for _, path := range paths {
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		content = manTitleDate.ReplaceAll(content, []byte(`${1}""`))
		content = manHistoryDate.ReplaceAll(content, []byte("$1"))
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return err
		}
	}
	return nil
}
